version: '3.8'

services:
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app_network
    container_name: ollama
    tty: true
    restart: unless-stopped

  fastapi:
    build: .
    container_name: backend
    ports:
      - "8000:8080"
    env_file:
      - .env
    networks:
      - app_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  ollama_data:
  huggingface_cache: